timezone: Asia/Seoul

# 네이버 뉴스 검색 페이지 수 (1페이지 ≈ 10개)
naver_pages: 8

keywords:
  - 아큐브
  - 쿠퍼 렌즈
  - 쿠퍼 비전
  - 쿠퍼비젼
  - 알콘 렌즈
  - 알콘
  - 다비치
  - 다비치 체인
  - 다비치 안경
  - 오렌즈
  - 난시렌즈
  - 난시용 렌즈
  - 나시용렌즈
  - 멀티포컬렌즈
  - 다초점 렌즈
  - 호야 렌즈
  - 자이스 렌즈
  - 콘택트렌즈
  - 으뜸50
  - 으뜸 플러스
  - 바슈롬
  - 인터로조
  - 소프트 콘택트렌즈
  - 컬러렌즈
  - 콘택트 렌즈
  - 한국존슨앤드존슨
  - 존슨앤드존슨 비전
  - 노안

  # 영문 병행
  - soft contact lens
  - multifocal lens
  - contact lens
  - ACUVUE
  - Alcon contact lens
  - CooperVision

news_sources:
  # 업계지 도메인 우선
  - name: 한국안경신문
    host: opticnews.co.kr
  - name: 안경계
    host: optic.or.kr
  - name: 데일리아이
    host: dailyeye.co.kr
  - name: FN아이포커스
    host: fneyefocus.com
  - name: 옵틱위클리
    host: opticweekly.com
  - name: 헬스조선
    host: health.chosun.com
  - name: 뉴시스
    host: newsis.com
  - name: 보건뉴스
    host: bosa.co.kr
  - name: 뉴스핌
    host: newspim.com

  # 구글 뉴스 전체 검색
  - name: 구글 뉴스(전체)
    host: ""

  # 네이버 뉴스
  - name: NaverNews
    host: ""

email:
  from: skim228@its.jnj.com
  to:
    - skim228@its.jnj.com
    - ylee73@its.jnj.com
  
    
  subject_prefix: "[ACUVUE Daily News]"
